### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by Deivis** [pagarme/react-scripts-former-kit-dashboard#23]
### Context

Update all major dependencies and fix interfaces and examples problems.

### Example
 
The update of this project will allow it dependencies to use new versions of tools like `babel`, `weback` and `react`which could improve the development speed and productivity.

### Description

This issue aims to upgrade all `dependencies` and all `devDependencies` of the project. The upgrade process may create some errors due to the dependencies interfaces, these errors should be solved in the upgrade process.
The major upgrades will be:
`babel` from version 6.26.0 to version 7.2.2
`jest` from version 22.1.4  to version  23.6.0 
`react` from version 16.2.0 to version 16.7.0
`webpack` from version 3.10.0 to version 4.28
 
### Requirements

- [x] Upgrade all outdated dependencies.
- [x] Refactor new dependencies interfaces usages.

**Comment by rsmelo** [comment]
publicado a versão 1.0.0 https://github.com/pagarme/react-scripts-former-kit-dashboard/releases/tag/1.0.0
